_target_: navsim.common.dataclasses.SceneFilter
_convert_: 'all'

num_history_frames: 4
num_future_frames: 10
frame_interval: null
has_route: true

max_scenes: null
log_names:
  - "2021.07.24.20.37.45_veh-17_00015_00375"
  - "2021.06.08.12.54.54_veh-26_04262_04732"
  - "2021.05.12.23.36.44_veh-35_01133_01535"
  - "2021.06.14.18.42.45_veh-12_03445_03902"
  - "2021.06.09.17.37.09_veh-12_00404_00864"
  - "2021.07.16.00.51.05_veh-17_01352_01901"
  - "2021.06.23.17.31.36_veh-16_00016_00377"
  - "2021.10.06.07.26.10_veh-52_00006_00398"
  - "2021.06.14.16.32.09_veh-35_05038_05402"
  - "2021.06.09.17.23.18_veh-38_00773_01140"
  - "2021.07.09.20.59.12_veh-38_01208_01692"
  - "2021.08.17.18.54.02_veh-45_00665_01065"
  - "2021.10.01.19.16.42_veh-28_03307_03808"
  - "2021.06.09.11.54.15_veh-12_04366_04810"
  - "2021.07.16.18.19.22_veh-35_00440_00858"
  - "2021.06.07.12.54.00_veh-35_01843_02314"
  - "2021.07.24.23.50.16_veh-17_01696_02071"
  - "2021.07.16.20.45.29_veh-35_00600_01084"
  - "2021.06.23.15.56.12_veh-16_00839_01285"
  - "2021.06.09.12.39.51_veh-26_05620_06003"
  - "2021.07.16.20.45.29_veh-35_01095_01486"
  - "2021.06.28.16.57.59_veh-26_00016_00484"
  - "2021.05.25.14.16.10_veh-35_01690_02183"
  - "2021.08.17.16.57.11_veh-08_01200_01636"
  - "2021.08.17.17.17.01_veh-45_02314_02798"
  - "2021.06.14.19.22.11_veh-38_01480_01860"
  - "2021.06.28.16.29.11_veh-38_03263_03766"
  - "2021.07.16.18.06.21_veh-38_04471_04922"
  - "2021.06.09.12.39.51_veh-26_01943_02303"
  - "2021.05.12.23.36.44_veh-35_00152_00504"
  - "2021.05.12.22.28.35_veh-35_00620_01164"
  - "2021.06.09.14.03.17_veh-12_02584_02970"
  - "2021.10.11.02.57.41_veh-50_00352_00535"
  - "2021.10.01.19.16.42_veh-28_02011_02410"
  - "2021.07.16.18.06.21_veh-38_03231_03712"
  - "2021.07.09.17.06.37_veh-35_00258_00748"
  - "2021.06.14.16.48.02_veh-12_04978_05337"
  - "2021.05.12.22.00.38_veh-35_01008_01518"
  - "2021.07.16.18.06.21_veh-38_04933_05307"
  - "2021.06.09.17.23.18_veh-38_02526_03027"
  - "2021.06.23.16.54.19_veh-35_00808_01256"
  - "2021.06.14.17.26.26_veh-38_04544_04920"
  - "2021.08.09.17.55.59_veh-28_00021_00307"
  - "2021.06.08.14.35.24_veh-26_02555_03004"
  - "2021.06.03.12.02.06_veh-35_00233_00609"
  - "2021.06.03.13.55.17_veh-35_00073_00426"
  - "2021.06.28.15.02.02_veh-38_02398_02848"
  - "2021.06.28.16.29.11_veh-38_01415_01821"
  - "2021.06.08.16.31.33_veh-38_01589_02072"
  - "2021.05.12.23.36.44_veh-35_02035_02387"
  - "2021.06.09.14.58.55_veh-35_01095_01484"
  - "2021.06.09.14.58.55_veh-35_01894_02311"
  - "2021.10.11.02.57.41_veh-50_01522_02088"
  - "2021.06.14.18.33.41_veh-35_03901_04264"
  - "2021.10.11.08.31.07_veh-50_01750_01948"
  - "2021.10.05.07.10.04_veh-52_01442_01802"
  - "2021.10.06.17.43.07_veh-28_00508_00877"
  - "2021.10.11.07.12.18_veh-50_00211_00304"
  - "2021.09.16.15.12.03_veh-42_01037_01434"
  - "2021.06.14.16.48.02_veh-12_04057_04438"
  - "2021.08.30.14.54.34_veh-40_00439_00835"
  - "2021.06.07.18.53.26_veh-26_00005_00427"

tokens:
 - "6774548111cb5ba4"
 - "09b2b571bb63520c"
 - "eaa80ba41cc55f65"
 - "aa96f52b95b155e7"
 - "f9b38490d7155d84"
 - "a49872d2b9165d3a"
 - "e63519408deb5931"
 - "dedb7c5e3604529e"
 - "83ee8f2c7d655e4b"
 - "ef43fe502d605e3b"
 - "e461c5837379517d"
 - "81765223f59055e3"
 - "a41654d17b2156e6"
 - "777f9bb032fa5e22"
 - "1d05dbff3a245c6b"
 - "6b8791b769f05a76"
 - "af4f40d2f07d5a92"
 - "f4db4b31f9265123"
 - "6e201d97d1ef5b4b"
 - "35d813d8de5854f9"
 - "a1440abecb1e5bb7"
 - "8d01189ae3605da4"
 - "028125098bb45d66"
 - "f62055fb4d8153a6"
 - "78e6ea95b854551c"
 - "8ed0f2cb1f2b5a8d"
 - "9228a7e1115d5bcd"
 - "dd3b8e9368be579f"
 - "525d50c3a0395264"
 - "7810122d0b665743"
 - "106da21b5dfd5c7e"
 - "a6e6dbdddc175b7b"
 - "7af34f0692605ad1"
 - "62981e97b1e35af5"
 - "12a68a4c440c5396"
 - "fc4ab990e1dc5729"
 - "5a8f0cf120495354"
 - "90a79351977a5f32"
 - "802ffb33c2655bab"
 - "4a3a4d54cc0851da"
 - "e269ac7ae792577b"
 - "add6e2410d5b5086"
 - "aa9a9fdb89275acb"
 - "e6acce4cea5152e2"
 - "2e0ec9c9c8fa51ba"
 - "077e96d483225276"
 - "4fea3406427a52de"
 - "2284b9d8a0f551b7"
 - "2111b648fcba5bb7"
 - "7fd9993b713f5c5d"
 - "9c633dbf7f8f5642"
 - "53b96dffa6df5f49"
 - "9f37b5755d545c9b"
 - "e4e9bb5cf9fb5e89"
 - "f1b03e919a945d9a"
 - "475241a1683159b9"
 - "47fc4cd82c45583c"
 - "64804276ef9559dc"
 - "b1b22a6803555b20"
 - "b01ded0854cc50fc"
 - "b8411116ac3355f3"
 - "601bc1f8a2dd5535"
 - "ab0473e852235c3a"
 - "cf8a7ca3e5d95343"
 - "4615024da7765d62"
 - "68c4d7e93cf55ccc"
 - "2d63eaba6813539f"
 - "4bb5e84b73765d38"
 - "fdc8022873e05a22"
 - "781efb1b870a58d4"
 - "e568957bee5b5b1e"
 - "996fd357a40d5a5a"
 - "d6ae2f654344509d"
 - "2f9035e24e0c5253"
 - "210dd1143b005422"
 - "abe70bb253d250e4"
 - "2533671fb5a05c8f"
 - "f95ed06f01b458a8"
 - "3aa75da19a2e55a8"
 - "3fa2f81cff025162"
 - "9b342d0967445869"
 - "8c9ee15aa2355c99"
 - "ba138477116b5956"
 - "2a7f092d10885cf1"
 - "02e78191bf845092"
 - "deb0dc3f9b1854fe"
 - "bd67b68fea295e96"
 - "94fa3bcc599852fa"
 - "8ec0cd02d7705766"
 - "46426db4636d52a9"
 - "b386ea967bea597c"
 - "40054f2ae3cd58e3"
 - "aa784b6564cb56a3"
 - "44c442cba5fe5f68"
 - "7200dcdd4ad05210"
 - "c4c63aa759ab5608"
 - "a7995c1f914c5d0d"
 - "e459687c42925b9a"
 - "243ea67f27195c7c"
 - "d1c281e277d1532d"
 - "b037a6dedefd50c0"
 - "a8c672e753205374"
 - "3c077c8da4615b33"
 - "3fbc9ed475f55789"
 - "143f361b85455570"
 - "e579b642c3845df8"
 - "bf44c74478445bdc"
 - "92a06bf5c99159f3"
 - "ed15c501931652d8"
 - "97e95edf011e57a0"
 - "5018ed61502d50f6"
 - "ead69cf7d81b5a39"
 - "3e0da2d159655124"
 - "258325ee3fe65b51"
 - "7e60d2df0fe75f4d"
 - "6fc06c6e4d1752a1"
 - "165e96e510d1580d"
 - "0612ae5a43ea5e14"
 - "a64cd79798845d53"
 - "e5a146299341551a"
 - "b2c8a3ec1fcc54e8"
 - "df98d316a00252ee"
 - "9b5c00687d4e590b"
 - "af9f5f6fa1ad5182"
 - "ddfbc4edaaae53b5"
 - "807dbc5ee447562b"
 - "65af3db384d05ac0"
 - "9ac3d5ecd8b55965"
 - "dcbf1cf262365995"
 - "94a77891082251d3"
 - "3ebe4c8a20155459"
 - "2c52f45993a257af"
 - "70df39aae7b05204"
 - "579f7ea85a0b56ee"
 - "452074cbdad6537b"
 - "d7ea3bb97a875a66"
 - "b30137ce1d255963"
 - "b44c4df580515280"
 - "624e63bf86d45ad7"
 - "8c2de95fb8a45d80"
 - "7543fb2f2dcf5c7e"
 - "27c35bdaec645591"
 - "69dbb083c75b5cf5"
 - "3b6e0e24fe5a5f5c"
 - "d38905854e5f55a3"
 - "32cdbb04af4856c0"
 - "8a2feb24de395309"
 - "9084cb3c199750e3"
 - "8e83aa46b4e350f0"
 - "7e1f829a0de95258"
 - "e6fb80d2ad2e53c3"
 - "8fb4110a350b5f17"
 - "48f75646bba35456"
 - "1267703b37a25911"
 - "3b96012de5d85ef5"
 - "299305dd47bc5d38"
 - "b5a0006f39005cee"
 - "ed43e43517f358d3"
 - "c18f8cfc41385d8c"
 - "710c63523d4d5e05"
 - "a1b3a17fb07c54ef"
 - "d6a0e6c1f41856ba"
 - "4a5e3ac0ccc75a68"
 - "b8a96fba2cbb5db5"
 - "f8e205ba18865d15"
 - "f0ac2804298b564f"
 - "1c4f3c5e6d2757a1"
 - "c6a199989fe9578f"
 - "83e30382af9d5c39"
 - "bd1e5e7e9c975f54"
 - "7c258cb6d64e5125"
 - "c97bad66929c58d1"
 - "5a728803325e5b78"
 - "3b33d44fb39a530b"
 - "63910f7e61dd5202"
 - "6e39441d943a59c2"
 - "7cc94c33bbe052d7"
 - "5d822115e0355e79"
 - "7b9cc1b02566583e"
 - "83812eaf10c25b0d"
 - "01cbcd1439e05cbc"
 - "5958ec1af5b1596d"
 - "9812dd2e53325739"
 - "c3710fb597c05b38"
 - "fc4af6a05e4e522e"
 - "d9d70933c5da52a2"
 - "ca9e7281adce5212"
 - "59e57a9c10e2553b"
 - "8eed113e54f65720"
 - "4d24781a33345c18"
 - "5d418a19150a56bb"
 - "fdae7ff3ee06523d"
 - "614792f42a2153a0"
 - "39130d1d9c3455e7"
 - "5b912402f6335fb1"
 - "0cd8b5151f03580f"
 - "b772d3f5334b52bb"
 - "ea963d5373bd5a56"
 - "65f1aecfc27158a7"
 - "a7289f730e7f5ef2"
 - "94f635177ffc585c"
 - "914ee770e05e5ba1"
 - "4fbb787fadf25c9c"
 - "b549b6c92312537d"
 - "307f5f9b4eeb517e"
 - "1ffe67c3104053f6"
 - "3d2d79069bb45530"
 - "f383acca25ff59eb"
 - "5ada4c7a67155a8f"
 - "f154d7cc016a59f9"
 - "077780f7790b584c"
 - "b4b65ccd6ba257e7"
 - "79bd7ba72d985b0b"
 - "a3870f56871e53d6"
 - "cdd7067da1925464"
 - "01d3a49577c256d6"
 - "c635be4959ce596a"
 - "9c3ce3b6a55c5907"
 - "aacf46ffaf2852f4"
 - "55fa5e002dfa56d0"
 - "1c669b68dc3d5689"
 - "3efa6ffa4fe25c6c"
 - "62b48ee81269527a"
 - "d5cf652a8ddf5a46"
 - "fbc2716d7a5d56e1"
 - "01a303fd4e9d54d5"
 - "272ca65d545a5e6d"
 - "0160a218dc9051bd"
 - "20f4b98587d25c47"
 - "e5e57399ea0a5228"
 - "834bb4167b885e57"
 - "a78c6c301bdc5573"
 - "1ca4fb094dd0522e"
 - "ab2748438f5d5a4d"
 - "c3e5047f2ff85e9a"
 - "1b55b0b3663c5224"
 - "639929a485e1582f"
 - "200da70adf745073"
 - "6bd5db4d9e095ecf"
 - "5ccd6d1ffdc752a8"
 - "d4c0bd232e0b5c6f"
 - "f8f68a72011f5946"
 - "e4549edf1d405a17"
 - "04135bd8a81759fa"
 - "22a56bd67d9c5183"
 - "0386720f697155c5"
 - "f30a714dd2af598d"
 - "8a61b6f43a50544d"
 - "a64559b4247653b7"
 - "1c6d28bbaa095e41"
 - "4584628100405d03"
 - "35d1e07f6df25694"
 - "21ba6fc7671d5a95"
 - "5dd66fecd1b4523b"
 - "3f12b84004b15310"
 - "d2f55d2de2175a6b"
 - "4789245424875682"
 - "f2f46b43681f5a58"
 - "e5f8dfb583be51bf"
 - "f6bb1b8ac5175173"
 - "f32a4e9c1f425498"
 - "8d7068683c385c08"
 - "9352f44f6db657df"
 - "71bd11736bca5299"
 - "a4baa9a721715069"
 - "e8c95dd46509501d"
 - "3cbed749b81d5b10"
 - "1e7bb5730b095273"
 - "8a94ea8cb82c55ad"
 - "d801a39fb8455204"
 - "735f3809d5215122"
 - "f0af55653c6252e7"
 - "a5efa651fec451b5"
 - "28f70bd9ad9f52b2"
 - "9610b02bc4ec529c"
 - "5d57c054b8155bd3"
 - "5e8f9f6ab5695769"
 - "2e186fa01d9a5c49"
 - "481eb6bee4545a5b"
 - "02536b72a70250d3"
 - "1f00a870fb3458b1"
 - "9ae5a292b89155a0"
 - "815132c8f2b4594e"
 - "cd00be51b43a5281"
 - "cc2769dbb64c51c5"
 - "900cf7a936095899"
 - "ac55f8a48f2f52d0"
 - "b18f531dcca75679"
 - "92b7fb405f2f5ccf"
 - "b3437b1cf6ee56d3"
 - "aba2ce98726d53d5"
 - "3c8b59aa1b175a25"
 - "b2f19dc9ecc052b4"
 - "f8490d92c5b65e2b"
 - "00b34c91088a5f04"
 - "27decc74a57b53ac"
 - "762599cde95156ff"
 - "4605de88aeb05903"
 - "18cf7d6f96f45847"
 - "7ff41f319fa05811"
 - "8465c2738bbc5faa"
 - "659676efe11b58ca"
 - "ac0c803827d65b80"
 - "d104844fde725c2a"
 - "618403c227415955"
 - "36b0118c36d95b3f"
 - "67ace6f3cd2051ef"
 - "7423d156df485c8b"
 - "08766082c4ef5ae8"
 - "494fade53c845a1b"
 - "88ea59b3f0235e02"
 - "d7aa6b013c7c56ec"
 - "885c3798916e5de8"
 - "3bff7854120758f4"
 - "9de4f939d84557e3"
 - "935eae9f2b155370"
 - "ec5e6f2f4d565c4c"
 - "755751098c88566f"
 - "19de57bdeb3052a4"
 - "e211bc381c495980"
 - "4a6671190875522e"
 - "ed76dc6f7f9c5109"
 - "c4458a8bf3e955e2"
 - "adfb4218735f5137"
 - "5ea3c0ec480e5213"
 - "b29743e5885f5514"
 - "92095189951055a5"
 - "cebac405bc31584f"
 - "b16709d711fd5097"
 - "78f39692bcf85cb2"
 - "00f53a22cb3e5bd6"
 - "449ee74c03685eee"
 - "6ed00f2d55aa51a8"
 - "e986ae1d5f0453db"
 - "71db290f69d9579e"
 - "b8e3585d666259f4"
 - "ac6d71dda508553f"
 - "c853ae7a361f54d9"
 - "72b0239d79175353"
 - "dace7f508e4b5070"
 - "0a8e8b7e94be5474"
 - "8561c627f83a5aac"
 - "d84f5656f4f753e4"
 - "18caa25c2a115f0a"
 - "32a3850fa50256fc"
 - "7a994056ade950d8"
 - "4d70b40e18c15498"
 - "83692bf833a15025"
 - "9690e454aaef531a"
 - "8ddcdb6f215b504c"
 - "b2ad937212f85714"
 - "faa042f84c4f585a"
 - "912445777d8c592b"
 - "8653e04dd5f75ec0"
 - "4b10d7d9e7465633"
 - "b84cc6bcd6d75173"
 - "8c2192a817225ae4"
 - "82385db0a426578d"
 - "61a58546ffef531e"
 - "f211df82899b5b78"
 - "2a1db78f15e55d74"
 - "70d3811d0cab5067"
 - "923dda2177545f0e"
 - "22f6e92516805d17"
 - "7496010433ac52fc"
 - "bad530d745d25cd7"
 - "1971c4278e675b9d"
 - "813b2926451158e8"
 - "669f927303ee54a8"
 - "98b18fb255445bb1"
 - "f057a88aaf1758b2"
 - "6f4131a328bc58b7"
 - "1b01b4ef87c951b7"
 - "3b8448effb715dc4"
 - "1fc1dd0dc3d157ae"
 - "6a75ce4874df52b7"
 - "43b5a9e3bd355d96"
 - "1c922a7f96245491"
 - "471f7ca3148659cd"
 - "1bac9ad3b5795fb9"
 - "fb8576d2ca7550e8"
 - "c18771a3868f5868"
 - "9632a1ccd0225e0d"
 - "f839f8d2874c5268"
 - "4ec9390e0cea5cde"
 - "94c075284a935bbb"
 - "9f379bc415ef56bc"
 - "724e53e4efef58b8"
 - "55842ddf5acd54a3"
 - "1bf100f880f558d6"
 - "ffcc82847bfb5568"
 - "402aa5d9a51e587c"
 - "e869951de22f5ecc"
 - "7aaa999404bc5b7e"
 - "379b9337542359bd"
 - "1872470c12e85ed8"
