_target_: navsim.common.dataclasses.SceneFilter
_convert_: all
num_history_frames: 4
num_future_frames: 8
frame_interval: 1
has_route: true
max_scenes: null
include_synthetic_scenes: true
log_names:
- '2021.08.16.14.23.37_veh-45_00015_00132'
- '2021.08.30.14.54.34_veh-40_00439_00835'
- '2021.09.16.15.47.30_veh-45_01199_01391'
- '2021.09.16.19.27.01_veh-45_01749_03230'
- '2021.09.29.14.44.26_veh-28_00528_00992'
- '2021.09.29.15.23.04_veh-28_00601_00802'
- '2021.09.29.19.02.14_veh-28_02911_03005'
- '2021.10.06.08.16.17_veh-52_01590_01725'
tokens:
- '0dc54a8c8203567b'
- '13310ca9a7715154'
- '19e90f2757b25f38'
- '2382542e05f253df'
- '3c542be991515ccd'
- '4cac9f6cd85a5b47'
- '5f53001e7e2d5347'
- '6326d00e52115da4'
- '67bce1e28df25eaa'
- '68097b10029d5fe1'
- '6e3cf172a2755fae'
- 'c054f473288d5515'
- 'd01fec804cd45644'
- 'ed3db88f99a05a6c'
- 'efa80e78fce1525d'
- 'f6b9867069845fd2'
reactive_synthetic_initial_tokens:
- '0395128411941228f'
- '03d0f73649589dca9'
- '052328b114b9c5cb5'
- '05d102dbfc508f379'
- '06082aa25b363522c'
- '063b137663ba8c507'
- '0923ee20dc5d20db6'
- '0a7e42966c6e6cce4'
- '0fd2976bdc791e64f'
- '102d8784884da0d54'
- '1061580743a8ed861'
- '10bdbc6a9b7b2bd43'
- '14ddd2546c5cda663'
- '151061d0d63eb2be6'
- '155fc3b8978be258b'
- '1574a4d082ac80b19'
- '15794da6178dc480a'
- '16be788d02f1fef14'
- '16e0a69867db58fda'
- '178a524a517377f19'
- '1853bf359b16c44e1'
- '18cda5f11659c3287'
- '1ac6bf0f26f45e643'
- '1bca89debb28211cf'
- '1c963497d68500ad1'
- '1cfd90c1b01a50afe'
- '1d00c1f1df43c8c01'
- '1e429d2f774768092'
- '1f2dfd2d3b74ad454'
- '2193125d732ee8d63'
- '22777eed80fe6c2f6'
- '2541602e453206839'
- '25b7f50ff65bf14c0'
- '267e63ac83466d214'
- '2693693ffe3ace9d7'
- '271bc2d78c35ee654'
- '28728be442990aea2'
- '2948ba510215527e5'
- '2e8f7bda514e182e8'
- '300c75247d0fbaeb8'
- '30442b44b719bcadc'
- '309c9042564f167ee'
- '314e1c5d77b802e7a'
- '31a41cd314e13595f'
- '3218bf90d6d24dc07'
- '326f9219f9a19b234'
- '35c0d827b75f88593'
- '35d06cd482bbccf6e'
- '36557ff78c024a815'
- '374858d4d47bbd16a'
- '3a3c5df8add8dc277'
- '3aa81c9276d98b0ab'
- '3ad3b5451829788bc'
- '3de8eff4da7a19f0f'
- '3e835a314f8e85e65'
- '3f785f1fec6b20810'
- '4010725f6359fa6d7'
- '4011e54d1cd33878d'
- '40592b30e67921dd9'
- '4068d8c6bdd0434cb'
- '41efad97268e1bea0'
- '420cf2b19dd7ceb38'
- '4291bb38d432590b4'
- '42fe9af736de10be8'
- '439515fa09c8b8c17'
- '44a0015fc40c1cb88'
- '44e909afb129ace3a'
- '44f56a3c522b7ea16'
- '454f5f1ed99b03e21'
- '462a33f831735c5b5'
- '467eb1f2d2e219049'
- '47531b5fa51305bdc'
- '47fb0d7e7e1751ffe'
- '484a304ef257656cd'
- '487a9143936d4df95'
- '488c24c04a2b22e40'
- '4a739fc19f2829e98'
- '4b5dc729abe1e75fe'
- '4c0a18dcc1cd87e5a'
- '4f486a22a5253de77'
- '50ab50f23e1e36c22'
- '50d3b8161a0e2ec5e'
- '514ba443c93be0c84'
- '543524873fd608480'
- '54f694f18d2befecc'
- '550e0654aa362120c'
- '55ae0fb023dccdeef'
- '5685730c604318275'
- '58ea88f6fa166c41d'
- '5b3d38f3a7038d843'
- '5c199633e69db185f'
- '5d58d417c1c5564c7'
- '5db0f2b89be2db1ed'
- '60b5b9341c2042487'
- '624d088d720311ed1'
- '62d82cda11d0f9b38'
- '62f565d438048059a'
- '6388350eec7089722'
- '6395dcf10e46c2df4'
- '63ddd50ee2f06d21e'
- '659c0196b18dee789'
- '65eb31b903d198175'
- '680330024974b3922'
- '688d1425020687afa'
- '68a8b0713f18185db'
- '6d179db1a50f4c602'
- '6dea4a1a6979c2797'
- '6df58e0094b1a82a5'
- '6eeb10e923eccae43'
- '7117885d184126d27'
- '7284fc567658fbe04'
- '73ca92fca40e84ca9'
- '75249638c881868c9'
- '75ddd45cee2b92f9f'
- '77107a2d9a5eb1301'
- '784776b37986bd743'
- '79f0721b30ab0e3d3'
- '7c07f70777a9d5e22'
- '7c2f2ad41acd928d7'
- '7cd03f87faa486284'
- '7e97ff6f6641a13f1'
- '7f12e0e132e710aa1'
- '8232d413132fd6755'
- '846aa1e0898aa0fd0'
- '854087b8099330cbb'
- '8683529f521965efb'
- '893336dcb0b52efed'
- '8b36f8a89f74b299b'
- '8b5b89a17f525c066'
- '8b8814727e2040c64'
- '8d909a1730d905741'
- '902320d7f1f9593e1'
- '91b676ab99380dae5'
- '925de5e162bda56b1'
- '940c8a566764b138f'
- '94edd98b10bee29f9'
- '95a1f61c556d4e7bb'
- '95b268581e07dfe75'
- '96ea7489c4ed725a8'
- '974cbc9e5430ffccb'
- '98b7bfbfa038695a8'
- '9e18abe750bbca914'
- '9fac3e2945fbb262f'
- 'a07f1969e1ecabd71'
- 'a10e31bb770227e1c'
- 'a356d1eec9561f41f'
- 'a53c4dbabccbf9ad7'
- 'a55f742686cf0e021'
- 'a779d4593119ba75d'
- 'a8b0630e7a0503603'
- 'a90e5a1d4e0eaf900'
- 'a9f3a0b070e956786'
- 'aa748e8b6e50c5aa2'
- 'aaa8ad268aeb2b33d'
- 'ac7cf00c976d1117c'
- 'acd702bf02f866713'
- 'aea520c78f8b94ce4'
- 'b0517afccc549cfa1'
- 'b29f5b928d8258e27'
- 'b4878f7f23f9a2d03'
- 'b5293d4480c7c425f'
- 'b59dbe7814a46d874'
- 'b5dc5725034e9698b'
- 'b80cec0f192c73ec8'
- 'b97724de6657d8a87'
- 'ba1811d57eb6e5fca'
- 'bbe5bcfd87eec2751'
- 'bd93ce3872b238f99'
- 'be48ae0d28bcf838c'
- 'be6f0a5cc43d23778'
- 'bf9caad8d0769b976'
- 'c062b247888baab11'
- 'c0a351e8e502a15c2'
- 'c2567200723a74dc4'
- 'c6640b50de9097a57'
- 'c67b6d22df8757dde'
- 'c67d22cbeb17a26dc'
- 'c68517f8b334e884d'
- 'c786e0464135c2ce2'
- 'ca648e31c14bd6d7b'
- 'ca7d4b2fe9e50ea90'
- 'cac747e1f9d79fb65'
- 'cb532e65ee0fb6214'
- 'cb62dae240fc0cfef'
- 'cc95e4a6ae9cd53dc'
- 'cce551cb57a2dadfb'
- 'ccfe0fb25455a6c23'
- 'cd6a11e595f9a52bc'
- 'cdcaf274771b9431a'
- 'cf8ccd6f64e2a2eb0'
- 'cfc3b4fce5ba4db5c'
- 'd036796570f6c1408'
- 'd14e7416564f243db'
- 'd2485e7a7ebeef7b4'
- 'd2bb1584003453202'
- 'd35e9678f254cab6a'
- 'd45e4b3b4680a10fe'
- 'd500c92f0a6d03763'
- 'd5cd6a5bbfa4a7cba'
- 'd7286e8accd37a650'
- 'd74ee03e2fc05b111'
- 'd7c22fdbafbc9e8e7'
- 'd88a4aa3fab405d76'
- 'd91bf2d4ee3b2aeb7'
- 'da30d8f979139b32c'
- 'db5b6cc66d7e4fb31'
- 'dc11a1e2bb4e6b9b8'
- 'dc401b1774612f61a'
- 'dd0c2f8d96f601b23'
- 'dd350799c316bcd2e'
- 'def9f9e2319514136'
- 'dfac4c9a0ecb22c25'
- 'e364916c9ca2c771c'
- 'e484a9def4ccefd34'
- 'e947e5fb3f2afafd1'
- 'eab4d52a75cf5303f'
- 'eaf5b61183e89a5f4'
- 'ebdb4044e28c31e1d'
- 'ec2382a1a500ca0e2'
- 'ecb720a8a00a2023c'
- 'eccb08b4729429873'
- 'ed1fa3b21e6fea4d2'
- 'eef3bc3f9753cbbdf'
- 'ef310cd99a8c34e5f'
- 'f0e56343f9478cde4'
- 'f1b5fa2dddcdb8ce2'
- 'f49b29b37a71f14b7'
- 'f6cf20eb11b17caba'
- 'f92a325de354a82d6'
- 'fab424b52bbed7a96'
- 'facd2351efa163724'
- 'fccd850b91749fce2'
- 'fd12d26948960e6a4'
- 'ff27ae550f0ce237b'
- 'ff631d75dff54b3a1'
- 'ffb2fa46014d4438d'
