hydra:
  run:
    dir: ${output_dir}
  output_subdir: ${output_dir}/code/hydra           # Store hydra's config breakdown here for debugging
  searchpath:                                       # Only <exp_dir> in these paths are discoverable
    - pkg://navsim.planning.script.config.common
  job:
    chdir: False

defaults:
  - default_common
  - default_evaluation
  - _self_
  - override train_test_split: navtest

submission_pickles: ??? # list of submission pickle directories
# - ...
# - ...


"team_name": ??? # The team name
"authors": ??? # The team members
"email": ??? # email of the corresponding team member
"institution": ??? # affiliation of the team
"country": ??? # country or region of the team, e.g. China
