_target_: nuplan.planning.scenario_builder.scenario_filter.ScenarioFilter
_convert_: 'all'

scenario_types: # List of scenario types to include
  - starting_left_turn
  - starting_right_turn
  - starting_straight_traffic_light_intersection_traversal
  - stopping_with_lead
  - high_lateral_acceleration
  - high_magnitude_speed
  - low_magnitude_speed
  - traversing_pickup_dropoff
  - waiting_for_pedestrian_to_cross
  - behind_long_vehicle
  - stationary_in_traffic
  - near_multiple_vehicles
  - changing_lane
  - following_lane_with_lead

scenario_tokens:
log_names: ${splitter.log_splits.val}
map_names: null

num_scenarios_per_type: 2
limit_total_scenarios: null
timestamp_threshold_s: 15
ego_displacement_minimum_m: null    # Whether to remove scenarios where the ego moves less than a certain amount
ego_start_speed_threshold: null     # Limit to scenarios where the ego reaches a certain speed from below
ego_stop_speed_threshold: null      # Limit to scenarios where the ego reaches a certain speed from above
speed_noise_tolerance: null         # Value at or below which a speed change between two timepoints should be ignored as noise.

expand_scenarios: false
remove_invalid_goals: true
shuffle: false
